### ISSUE TITLE
Make name editable on profile

### ISSUE THREAD

**Issue by colin4554** [GTBitsOfGood/helping-mamas#101]
### Overview
Make the first and last name editable on the profile page

### Details
- The only field that shouldn't be editable is the email address and total hours

**Comment by VedanthB** [comment]
Hey, id like to give this a try

**Comment by YiQin93** [comment]
The interface looks great! But the edits are not saved.

Please view this report for more details: https://go.playerzero.app/share/63534140f4cd56bc30541c98
