### ISSUE TITLE
Fix Nav bar styles

### ISSUE THREAD

**Issue by colin4554** [GTBitsOfGood/helping-mamas#102]
### Overview
A couple style updates to the nav bar.

### Details
- Increase the font-size of the “Settings” tab to be consistent with the others.
- Admin view: Fix the background color of the subtabs of “Settings” and Profile on hover **and** click
- Volunteer view: Same thing with Profile tab
- There should be 1 color that fills the entire item (gray for hover, red for click)
- View example screenshots [here](https://gtbitsofgood.notion.site/Nav-bar-style-examples-185990f955554d4cb482f3982374c122)

**Comment by KaptainCS3** [comment]
Assign me

**Comment by YiQin93** [comment]
- The hover & click colors look perfect!
- But the font size of the settings tab still does not look very consistent with others on my end.

![image](https://user-images.githubusercontent.com/65053210/190538584-4724761a-4ff7-41c4-9e59-e349a46a195d.png)
