### ISSUE TITLE
Volunteer Registration Improvements

### ISSUE THREAD

**Issue by colin4554** [GTBitsOfGood/helping-mamas#154]
### Overview
Polish the volunteer registration process.

### Details
This is a front-end task divided into 2 sections:

**During Registration:**

- [x] Currently, the waiver checkbox is the same for Minors and Guardian. Change it so selecting one doesn't also select the other. Also, the Next or Register button should be disabled if the checkbox is not checked.
- [x] Change the Minor card to say "Minor with fname lname" of the adult that added them.
- [x] Display the right contact information (Event Contact section of event)

**After Registration Confirmation:**
- [x] Change the header from "Registration Confirmed" to "Your've signed up successfully!".
- [x] #189
- [x] Change the "We've sent a confirmation email." to "Please check your mailbox for a confirmation email."
- [x] #196
- [x] Move the "Return to Home" button to be under the “Resend confirmation”, “View waivers”, and “Cancel registration” buttons.
- [x] Remove the add minor link.

**Both Steps**
- [x] View Figma under [Register Event](https://www.figma.com/file/LEZGE9yXVag3LY8zHACAY5/Helping-Mamas-%2F-Spr2022?node-id=1%3A3)
- [x] Visit Event Page link should be moved to event card and the text changed to "See full event information"
- [x] Display the full address
- [x] Remove court required hours checkbox, replace the sentence with "If a minor under 13-year-old will volunteer with you, please add their information below. Note: Minors at or above 13-year-old need to sign up using their own account."
- [x] Move "Add Minor" button to right side of minor containers (put minor containers in a flex grid so the button gets move to the right when new minors are added)
- [x] On "Add Minor" popup, change the "Add and Close" & "Add Another" buttons to "Cancel" & "Add".
- [x] On Waiver popup with no minors, add text "If you are under 18, the waiver must be signed by your parent"
- [ ] #197
- [x] Change the "Complete Registration" button to not be fixed at the bottom. Remove its white background and place it - under the participants' cards with some padding. Change the text to "Sign up".

**Comment by colin4554** [comment]
`  const onUnregister = async (event) => {
    const changedEvent = {
      // remove current user id from event volunteers
      ...event,
      minors: event.minors.filter(
          (minor) => minor.volunteer_id !== user._id
      ),
      volunteers: event.volunteers.filter(
        (volunteer) => volunteer !== user._id
      ),
    };`

line 131 of event manager.jsx in screens/

**Comment by YiQin93** [comment]
Amazing work! It looks much prettier now!

A couple of issues:
1. [High Priority] When adding a minor and clicking the cancel button, the minor is currently still being added.
2. [High Priority] When a guardian tries to sign both waivers for themselves and their minors, they could still sign up if only the minors' box is checked.
3. [Medium Priority] When a guardian reviews the waivers after they've signed up, they can only review waivers for themselves, but they should also be able to view that for their minors.
4. [Low Priority] When multiple minors are added, the background cards stick together, which is not desired.

Please see more details in this report: https://go.playerzero.app/share/637146495a55a8bd23d18504

**Comment by colin4554** [comment]
I fixed issues 1 and 2, Phoebe fixed issue 4.

**Comment by YiQin93** [comment]
This looks awesome! Yayyay!!
