### ISSUE TITLE
Standardize time/date

### ISSUE THREAD

**Issue by colin4554** [GTBitsOfGood/helping-mamas#217]
All time/date should be stored and compared in UTC for attendance. It should be presented in the UI in the user's timezone.

This needs to be cleaned up a lot

**Comment by colin4554** [comment]
On the UI, when the admin is editing time cards only allow the check-out time to be in the future (and the check-in time in the past).

**Comment by YiQin93** [comment]
There is a small issue with editing the check-out time on the time cards:
- Edit volunteer check-in and out time doesn't update until refreshing the page - if I previously typed in an incorrect check-out time (a check-out time that is earlier than the check-in time) during this update
- Please find more details in this report: https://go.playerzero.app/share/63f427f2e059aae6d7a6ecb2

But this would be a low priority as this event has a small-probability.
