### ISSUE TITLE
Add Calendar Legend

### ISSUE THREAD

**Issue by colin4554** [GTBitsOfGood/helping-mamas#233]
### Overview
 On the Events page, add a legend underneath the calendar.

### Details
- The legend should always be displayed (regardless if the user is an admin or volunteer)
- Reference the [Figma](https://www.figma.com/file/ETUKCDm2THyAdUsRpWlPlM/Helping-Mamas-%2F-Spr23?node-id=2675%3A28708&t=CwnQr3QRR8IKVKVz-1) for the legend. Simply display it as an image. You should be able to directly download this image:
![Calendar Legend](https://user-images.githubusercontent.com/65053210/215344455-bdcf046a-4a9f-4714-aec5-1ed9d640c344.svg)

- In sum, it should be two elements: the text and an image.

**Comment by YiQin93** [comment]
This looks awesome!
