### ISSUE TITLE
Replace all Tables

### ISSUE THREAD

**Issue by colin4554** [GTBitsOfGood/helping-mamas#242]
### Overview
Replace all tables in the application for better design and mobile responsiveness.

### Details
- Use https://flowbite-react.com/tables
- Replace tables for EventTable, Attendance, EventHistory, etc.
- One all tables are replaced, delete all unnecessary code/files related to table styling.

**Comment by cduffy8** [comment]
Currently Experiencing Issues testing if my change in EventTable is working for individual stats because, I'm getting errors anytime I look at user stats for a user that has volunteered for at least one event.

**Comment by cduffy8** [comment]
Should I convert the table in Profile Form? It uses this `import * as Table from "../sharedStyles/tableStyles";' but looks like it's actually a form.

**Comment by colin4554** [comment]
> Currently Experiencing Issues testing if my change in EventTable is working for individual stats because, I'm getting errors anytime I look at user stats for a user that has volunteered for at least one event.

Can you paste the error?

**Comment by colin4554** [comment]
> Should I convert the table in Profile Form? It uses this `import * as Table from "../sharedStyles/tableStyles";' but looks like it's actually a form.

You can ignore that

**Comment by cduffy8** [comment]
> > Currently Experiencing Issues testing if my change in EventTable is working for individual stats because, I'm getting errors anytime I look at user stats for a user that has volunteered for at least one event.
> 
> Can you paste the error?

Resolved

**Comment by cduffy8** [comment]
I didn't mess with the original way it was doing the linking either. Looks like there's some events with the same id causing an issue whenever I try and use that as a key.
