### ISSUE TITLE
Combine all the User edit front ends

### ISSUE THREAD

**Issue by colin4554** [GTBitsOfGood/helping-mamas#248]
### Overview
Consolidate the User Edit Forms into one component

### Details
- Currently, the user edit form is in 3 locations (edit admin, edit volunteer, edit profile)
- It should be extracted into one component and then used in the 3 locations as <UserEditForm> or something similar
- Update the forms to use the new InputField component within our app
- A few changes are required
  - Hide the role dropdown everywhere
  - Only show notes if an admin is logged in
  - Only allow edits to edit profile and edit volunteer (you can pass in a boolean and disable all the fields if true).

**Comment by cduffy8** [comment]
What do you mean by this "Only allow edits to edit profile and edit volunteer (you can pass in a boolean and disable all the fields if true)."

**Comment by colin4554** [comment]
Admins can't edit other admins' data. If a boolean prop to the component is true, all the fields should be disabled. You will have to add the disabled ability to the InputField component on Austin's Sprint 2 branch
