### ISSUE TITLE
Combine Events and Past Events pages

### ISSUE THREAD

**Issue by colin4554** [GTBitsOfGood/helping-mamas#96]
### Overview
Combine the Events and Past Events pages into one page called Events

### Details
- Change needed on both the Admin **and** volunteer view
- The finished page should have both the back to today (this functionality may need to be fixed) and Create Event buttons
- Past events should be displayed when clicking on a previous date

**Comment by YiQin93** [comment]
Did not test for "Past events should be displayed when clicking on a previous date". There are currently no events on a previous date.
