### ISSUE TITLE
Create Group Events

### ISSUE THREAD

**Issue by colin4554** [GTBitsOfGood/helping-mamas#97]
### Overview
Allow admins to create Group Events

### Details
- On the create event modal have two tab options, one for Group Events and one for Standard Events
- Design should look like [the Create Event Design](https://www.figma.com/file/LEZGE9yXVag3LY8zHACAY5/Helping-Mamas-%2F-Spr2022)
- Organization Information should be viewable by the admin when viewing a specific event

**Comment by YiQin93** [comment]
There are a couple of issues with this pull request:
1. The _Standard Event_ tab and the _Group Event_ tab are currently switched.
2. The _organization information_ is not shown on the _Event Page_.
3. The event creation time on the _Event Page_ is incorrect.
4. There are no fields to input the _event host's contact information_ as we create an event, and this information is not displayed on the _Event Page_ (We may need to rearrange the _Event Information_ section when creating an event).

Please see this report for more details: https://go.playerzero.app/share/632b79b86e4db9da68e5a342
